trainer:
  gpus: 1  # single GPU training
  min_epochs: 20
  max_epochs: 100
  benchmark: True

experiment:
  task: "urban3dchallenge"
  module:
    loss: "ce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 6
    num_classes: 2
  datamodule:
    batch_size: 4
    num_workers: 4
