experiment:
  task: "urban3dchallenge"
  module:
    loss: "ce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: null
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 6
    num_classes: 2
    ignore_zeros: True
  datamodule:
    root_dir: "tests/data/urban3d"
    batch_size: 8
    num_workers: 0
